webdev/task/urls.py
from django.urls import path
from .views import home 
from .views import detail
from .views import delete

app_name = 'task'

urlpatterns = [
    path('', home, name='home'),
    path('<int:task_id>', detail, name='detail'),
    path('delete/<int:task_id>', delete, name='delete')
]

webdev/urls.py
from django.contrib import admin
from django.urls import path, include
from webdev.home_view import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('task/', include('webdev.task.urls')),
]

webdev/task/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=50)
    done = models.BooleanField(default=False)

webdev/task/forms.py
from django.forms import ModelForm
from webdev.task.models import Task    


class TaskNewForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name']

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'done']
    

webdev/task/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from webdev.task.forms import TaskNewForm
from webdev.task.forms import TaskForm
from django.urls import reverse
from webdev.task.models import Task


def home(request):
    if request.method == 'POST':
        form = TaskNewForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('task:home'))
        else:
            task_bagger = Task.objects.filter(done=False).all()
            task_done = Task.objects.filter(done=True).all()
            return render(
                request, 'task/home.html', 
                {
                    'form':form, 
                    'task_bagger': task_bagger,
                    'task_done': task_done,
                    }, 
                    status=400)
    task_bagger = Task.objects.filter(done=False).all()  
    task_done = Task.objects.filter(done=True).all()
    return render(request, 'task/home.html',
                    {
                        'task_bagger': task_bagger,
                        'task_done':task_done,
                    })

def detail(request, task_id):
    if request.method == 'POST':
        task = Task.objects.get(id=task_id)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect(reverse('task:home'))

def delete(request, task_id):
    if request.method =='POST':
        Task.objects.filter(id=task_id).delete()
    return HttpResponseRedirect(reverse('task:home'))

webdev/task/templates/task/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Lista de Tarefas</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 ofsset-md-2">
            <h1 class="mt-5">Lista de Tarefas</h1>

            <form action="{% url 'task:home' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Descreva sua Tarefa" aria-label="Descreva sua Tarefa" aria-describedby="button-addon2" name="name">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary" type="submit" id="button-addon2">Salvar</button>
                    </div>
                </div>  
                <small class="form-text text-muted">{{ form.name.errors }}.</small>
            </form>

            <h2 class="mt-5">Tarefas Pendentes</h2>

            {% for task in task_bagger %}
                <form action="{% url 'task:detail' task_id=task.id %}" method="post">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Descreva sua Tarefa" required='required' aria-label="Descreva sua Tarefa" name="name" value="{{ task.name }}">
                        <input type="hidden" value="checked" name="done">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-success"  id="button-addon2">Marcar Como Feito</button>
                        </div>
                    </div>  
         
                </form>

             {% endfor %}

             <h2 class="mt-5">Tarefas Realizadas</h2>
               
            {% for task in task_done %}

                <div class="row">
                    <div class="col-2">
                        <form action="{% url 'task:delete' task_id=task.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-danger"  id="button-addon2">Apagar</button>
                                </div>
                            </div>  
            
                        </form>
                    </div>
                <div class="col-10">
                    <form action="{% url 'task:detail' task_id=task.id %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Descreva sua Tarefa" required='required' aria-label="Descreva sua Tarefa" name="name" value="{{ task.name }}">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-warning"  id="button-addon2">Marcar Como Pendente</button>
                            </div>
                        </div>  
            
                    </form>
                </div/>
            </div>   

        {% endfor %}
        </div>
    </div>



</div>
</body>
</html>